### ISSUE TITLE
A better file extension

### ISSUE THREAD

**Issue by lgrozinger** [intbio-ncl/shortbol#11]
.rdfsh is awful

I propose that, either the compiler is extension-agnostic (doesn't care about anything after the dot).

OR

file extension .sbol

Thoughts?

**Comment by jakebeal** [comment]
Is this for the ShortBOL input or the SBOL output?

For ShortBOL input, I don't think it should be .sbol, since that will confuse with the output.
I'd go for either agnostic (any text file) or something like ".shb"

For SBOL output, it should be .xml (or whatever alternate serialization, like .json)

**Comment by MattyCrowther** [comment]
I believe the tool is file-type agnostic isn't it?
I can't find anywhere that checks and I can run the tool with any and no filetype
Maybe we should keep the agnostic filetype behaviour but have a standard of .shb?

**Comment by MattyCrowther** [comment]
This is for both I & O

**Comment by MattyCrowther** [comment]
(The tool being filetype agnostic)

**Comment by MattyCrowther** [comment]
Closing this ticket as I don't think there is an issue. I plan to change the standard file extension for the template library to .shb but any file doesn't have to be a certain file type anyway so I don't think it is an issue.
