### ISSUE TITLE
Distribution of ShortBOL

### ISSUE THREAD

**Issue by MattyCrowther** [intbio-ncl/shortbol#14]
As ShortBOL becomes more accessible to non-computational users it doesn't make sense for the usage (having to input the relativley unintuitive commands in the shell) to be the only way to use the tool.

the current input requires you to navigate to the runner file and input something like:
`python3.6 run.py -s sbolxml /examples/simple_example.rdfsh -o output.xml`
Even though we do have the web application it was never intended to be the primary method for somebody to use the tool. (Even though its getting better than the initial version).
I can't see ShortBOL being used with these avenues of usage only.

Some ideas:

- distutils and/or Py2exe

-  Create a standalone binary that spawns a simple GUI for programming.

- Integration into IDE's

-  Automatic Integration into the PYTHONPATH so the user can literally type something like:
shortbol my_shortbol_script.rdfsh

- A simple pip install shortbol.

I would be interested to hear from people who have more experience with python distribution.
@jakebeal @lgrozinger @bbartley @udp

**Comment by lgrozinger** [comment]
A lot of the typing in the example could be eliminated by setting sensible defaults. 

For example, the serialisation default was turtle when the project was called `rdfscript`, because it didn't make sense then for it to assume SBOL as default. Now, if you package things as a ShortBOL application, obviously the default could be SBOL/XML. I'm sure the output filename could also be given a sensible default.

As for the standalone idea `distutils` would be my preference (with the sensible defaults mentioned above).

Some other comments:

> Create a standalone binary that spawns a simple GUI for programming.
This is a great idea that I'm not excited about at all.

> Automatic Integration into the PYTHONPATH so the user can literally type something like:
> shortbol my_shortbol_script.rdfsh
I don't like playing with people's paths, etc.
